services:
  dev:
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=/mnt/wslg/PulseServer
      - MUJOCO_GL=glfw
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg